### ISSUE TITLE
:get_state is unnecessary

### ISSUE THREAD

**Issue by ruslandoga** [general-CbIC/poolex#115]
👋 

https://github.com/general-CbIC/poolex/blob/1a819538b06f3a3cd80f9a3cb67f40d72f737f47/lib/poolex.ex#L395-L397

can be replaced with `:sys.get_state`: https://www.erlang.org/doc/apps/stdlib/sys.html#get_state/1 It has pretty much identical implementation.

The reasoning is that cutting down on custom stuff like this and delegating to Erlang VM would make the codebase smaller and easier to understand. And improvements in the underlying implementations would translate to zero effort improvements to the library.

**Comment by general-CbIC** [comment]
Hi! 👋🏻 
Thanks for the issue 🙏🏻 

`Poolex.get_state/1` was deprecated in [v1.1.0](https://github.com/general-CbIC/poolex/releases/tag/v1.1.0).
