### ISSUE TITLE
Shutdown process

### ISSUE THREAD

**Issue by alexcastano** [general-CbIC/poolex#44]
Hello!

It seems like the library doesn't handle the shutdown process. The pool dies but the workers are still alive, which is very inconvenient. I took a quick look at poolboy and it uses a supervisor where the workers are placed to handle the shutdown process correctly. Do you have a plan to do something similar?

Thank you!

**Comment by general-CbIC** [comment]
Hello!

Thank you for your issue!

This is a bug. `Poolex` also uses [supervisor](https://github.com/general-CbIC/poolex/blob/develop/lib/poolex/supervisor.ex) to run workers under it. But it seems the current implementation missed an important [terminate](https://hexdocs.pm/elixir/1.14.5/GenServer.html#c:terminate/2) callback. I will fix it.

It will help a lot if you tell me how to reproduce this situation :)

**Comment by general-CbIC** [comment]
Hello, @alexcastano!

The bug should have been fixed in version **[0.7.1](https://github.com/general-CbIC/poolex/releases/tag/v0.7.1)**.

**Comment by alexcastano** [comment]
Excellent work!! 👏🏻 👏🏻 ❤️
