### ISSUE TITLE
Poolex doesn't verify if there are callers after a worker dies

### ISSUE THREAD

**Issue by alexcastano** [general-CbIC/poolex#53]
I didn't create a test, but I think when a worker dies Poolex doesn't verify if there are new callers waiting for a worker:
https://github.com/general-CbIC/poolex/blob/main/lib/poolex.ex#L449-L482

We do here for example:
https://github.com/general-CbIC/poolex/blob/main/lib/poolex.ex#L401

I also think that Poolex wouldn't need to make a difference between a "temporary worker" and a "regular worker", and it could make the code easier (less complex). We only need to verify the number the workers and the configuration params:

If a worker dies, we remove it from the list of workers, and then:
  * We check if there are pending callers, we create a new worker
  * If not we check if the number of current workers is less than minimum, then we create a new worker.
  * Else, we remove don't create a new one.

Similarly, when a worker is released:
  * If we have pending callers, we send the worker to the caller
  * If the number of the current workers is in overflow, we kill it.
  * If not, we put it on the idle list.

I hope it helps

**Comment by general-CbIC** [comment]
Hello!

Thanks, I reproduced the issue. Fixes are coming soon :)

I'm not sure about regular and temporary workers, as I've been implementing them for quite some time :(
Now I do not see such a global difference between them, so I agree. I will try to simplify the code.
